values = [
    'Applicant Connection Request Type Details',
    'Application Type',
    'New Licence',
    'Firm Type',
    'Proprietary',
    'Category Type',
    'Others',
    'Type of Ownership of Business Premises',
    'On Rent',
    'License No_',
    'RAN22101019174908',
    'Applicant Details',
    'SNo',
    'Applicant Name',
    'KRISHNA KUMAR GOENKA',
    'Father Name',
    'LATE JAGDISH PRASAD GOENKA',
    'Ward No1',
    'Mobile No',
    '9835152534',
    'Pan No',
    'XXXXXXXX',
    'Aadhar No',
    'XXXXXXXX8187',
    'Applicant Address',
    'NEAR GOPAL COMPLEX 88 KUTCHERY ROAD RANCHI',
    'Email Id',
    'Details Of Business (Please fill in capital letters)',
    'Ward No2',
    '22',
    'Holding(lf Any) No',
    'Name of Business Firm',
    'GANPAT RAI MOTILAL',
    'Nature of Business Firm',
    '1. CLOTH OR CLOTHES OF COTTON WOOL SILK ART SILK ETC EXCEPT FOR DOMESTICS',
    'Name Of Owner of Business Premises.',
    'NA',
    'Brief Description of Business Firm',
    'CLOTH',
    'Date of Establishment',
    '13-09-20191',
    'PAN No(lf any)',
    'TIN No(lf any)',
    'Sales Tax No (If any)',
    'Business Address',
    'MAIN ROAD RANCHI JHARKHAND',
    'Street Name',
    'Annual Turnover of Business (in Rs)',
    'KNo_',
    'Total Area (Sq.Ft:)',
    '450',
    'Total Area (Sq.Meter:)',
    '41.80',
    'Bind/Book No.',
    'Account No.',
    'Bussiness Mobile No_',
    'XXXXXXXX34',
    'Payment Detail',
    'Processing Fee',
    '500.00',
    'Payment Through',
    'CASH',
    'Challan No',
    '67148130919033801',
    'Transaction Date',
    '13-09-20192']

final_labellist = [
    'Application Type',
    'License No.',
    'Firm Type',
    'Type of Ownership of Business Premises',
    'Applicant Name',
    "Father's Name",
    'Mobile No.',
    'Applicant Address',
    'Name of Business',
    ' Nature of Business/Brief Description of Business',
    ' Date of Establishment',
    ' Business Address',
    ' Total Area (Sq.Ft.)']

final_dict = {}
for i in final_labellist:
    for j in values:
        if (i == j):
            final_dict.update({i: values[values.index(i) + 1]})

print(final_dict)